/* ===================== 이룸토익 LMS · 빈출 어휘 데이터 =====================

   분류 기준
   ETS 가 공식 안내서에서 밝힌 TOEIC Listening & Reading 출제 영역 13개를
   그대로 주제로 삼았습니다. (Corporate Development / Dining Out / Entertainment /
   Finance and Budgeting / General Business / Health / Housing·Corporate Property /
   Manufacturing / Offices / Personnel / Purchasing / Technical Areas / Travel)
   출처: ETS TOEIC Listening and Reading Test Examinee Handbook

   각 단어에 붙는 정보
   - w    단어
   - pos  품사 (n 명사 · v 동사 · a 형용사 · ad 부사 · phr 표현)
   - mean 뜻
   - theme 주제 (위 13개 중 하나)
   - parts 주로 나오는 파트
   - lv   난이도 1 기초 · 2 중급 · 3 고급
   - ex / exK 예문과 해석 (토익에 나오는 문장 형태로 씀)
   - col  콜로케이션 — Part 5 어휘 문제는 「어떤 단어와 짝을 이루는가」로 갈립니다
   - syn  동의어 — Part 7 은 지문 표현을 선택지에서 다른 말로 바꿔 씁니다(패러프레이징)
   - conf 혼동어휘·파생어 — 형태가 비슷해 오답으로 자주 깔립니다
   ========================================================================= */

const TO_THEMES = [
  {k:'office',  name:'사무 · 업무',      sub:'회의 · 문서 · 사무기기 · 업무 절차',   color:'#0d9488'},
  {k:'hr',      name:'인사 · 채용',      sub:'채용 · 승진 · 급여 · 퇴직 · 복리후생', color:'#2563eb'},
  {k:'biz',     name:'일반 비즈니스',    sub:'계약 · 협상 · 마케팅 · 영업 · 보증',   color:'#7c3aed'},
  {k:'fin',     name:'재무 · 예산',      sub:'은행 · 투자 · 세금 · 회계 · 청구',     color:'#c2410c'},
  {k:'purch',   name:'구매 · 배송',      sub:'주문 · 비품 · 발송 · 송장',            color:'#b45309'},
  {k:'travel',  name:'출장 · 여행',      sub:'항공 · 호텔 · 예약 · 지연 · 렌터카',   color:'#0891b2'},
  {k:'manu',    name:'제조 · 생산',      sub:'생산라인 · 공장 관리 · 품질 관리',     color:'#4338ca'},
  {k:'tech',    name:'기술 · IT',        sub:'전자 · 컴퓨터 · 실험 · 기술 규격',     color:'#0369a1'},
  {k:'house',   name:'주택 · 부동산',    sub:'건설 · 시공 · 매매 · 임대 · 공공요금', color:'#a21caf'},
  {k:'corp',    name:'기업 개발',        sub:'연구 · 제품 개발',                     color:'#059669'},
  {k:'dine',    name:'식사 · 행사',      sub:'식당 예약 · 연회 · 케이터링',          color:'#db2777'},
  {k:'ent',     name:'문화 · 여가',      sub:'공연 · 영화 · 전시 · 미술관 · 매체',   color:'#9333ea'},
  {k:'health',  name:'보건 · 의료',      sub:'병원 · 진료 · 의료보험',               color:'#dc2626'}
];
function toTheme(k){ return TO_THEMES.find(function(t){ return t.k===k; }) || {k:k,name:k,sub:'',color:'#94a3b8'}; }
function toThemeName(k){ return toTheme(k).name; }

const TO_POS = { n:'명사', v:'동사', a:'형용사', ad:'부사', phr:'표현' };
function toPosName(p){ return TO_POS[p] || p; }

/* ======================= 사무 · 업무 (Offices) ======================= */
const TO_VOCA_SEED = [
{id:'v001', w:'agenda', pos:'n', mean:'안건, 회의 순서', theme:'office', parts:[4,6,7], lv:1,
 ex:'Please review the agenda before tomorrow\'s board meeting.', exK:'내일 이사회 전에 안건을 검토해 주세요.',
 col:'on the agenda 안건에 올라 있다 / set the agenda 안건을 정하다', syn:'schedule, program', conf:'agent(n. 대리인)'},
{id:'v002', w:'minutes', pos:'n', mean:'회의록', theme:'office', parts:[6,7], lv:2,
 ex:'The minutes of the meeting will be distributed by e-mail.', exK:'회의록은 이메일로 배포될 것입니다.',
 col:'take the minutes 회의록을 작성하다', syn:'record, transcript', conf:'단수 minute(분)와 뜻이 다릅니다'},
{id:'v003', w:'memorandum', pos:'n', mean:'회람, 사내 공문 (memo)', theme:'office', parts:[6,7], lv:2,
 ex:'A memorandum about the new dress code was posted this morning.', exK:'새 복장 규정에 관한 회람이 오늘 아침 게시되었습니다.',
 col:'issue a memorandum 회람을 내다', syn:'notice, circular', conf:'memoir(n. 회고록)'},
{id:'v004', w:'distribute', pos:'v', mean:'배포하다, 나누어 주다', theme:'office', parts:[4,5,6], lv:1,
 ex:'Handouts will be distributed at the entrance.', exK:'유인물은 입구에서 배포됩니다.',
 col:'distribute copies 사본을 나눠 주다', syn:'hand out, circulate', conf:'contribute(v. 기여하다)'},
{id:'v005', w:'reschedule', pos:'v', mean:'일정을 다시 잡다', theme:'office', parts:[3,4,7], lv:1,
 ex:'We had to reschedule the interview for Thursday.', exK:'면접 일정을 목요일로 다시 잡아야 했습니다.',
 col:'reschedule an appointment 약속을 변경하다', syn:'postpone, move', conf:'schedule(v. 일정을 잡다)'},
{id:'v006', w:'postpone', pos:'v', mean:'연기하다, 미루다', theme:'office', parts:[3,5,7], lv:1,
 ex:'The workshop has been postponed until further notice.', exK:'워크숍은 추후 안내가 있을 때까지 연기되었습니다.',
 col:'postpone indefinitely 무기한 연기하다', syn:'delay, put off, defer', conf:'전치사 until 과 씁니다'},
{id:'v007', w:'attend', pos:'v', mean:'참석하다', theme:'office', parts:[3,4,5], lv:1,
 ex:'All department heads are required to attend the session.', exK:'모든 부서장은 그 회의에 참석해야 합니다.',
 col:'attend a conference 학회에 참석하다', syn:'be present at, participate in', conf:'attend to(~을 처리하다) — 전치사가 붙으면 뜻이 달라집니다'},
{id:'v008', w:'confirm', pos:'v', mean:'확정하다, 확인해 주다', theme:'office', parts:[3,5,7], lv:1,
 ex:'Please confirm your attendance by Friday.', exK:'금요일까지 참석 여부를 확정해 주세요.',
 col:'confirm a reservation 예약을 확인하다', syn:'verify, validate', conf:'conform(v. 따르다, 순응하다)'},
{id:'v009', w:'notify', pos:'v', mean:'통보하다, 알리다', theme:'office', parts:[4,5,6], lv:2,
 ex:'Employees will be notified of the change in advance.', exK:'직원들은 변경 사항을 사전에 통보받을 것입니다.',
 col:'notify + 사람 + of + 내용', syn:'inform, advise', conf:'notify 는 사람을 목적어로, announce 는 내용을 목적어로 씁니다'},
{id:'v010', w:'submit', pos:'v', mean:'제출하다', theme:'office', parts:[5,6,7], lv:1,
 ex:'Reimbursement forms must be submitted within 30 days.', exK:'환급 신청서는 30일 이내에 제출해야 합니다.',
 col:'submit a proposal 제안서를 제출하다', syn:'turn in, hand in, file', conf:'summit(n. 정상, 정상회담)'},
{id:'v011', w:'revise', pos:'v', mean:'수정하다, 개정하다', theme:'office', parts:[5,6,7], lv:2,
 ex:'The manual was revised to reflect the new procedure.', exK:'설명서는 새 절차를 반영해 개정되었습니다.',
 col:'a revised edition 개정판', syn:'amend, update, modify', conf:'devise(v. 고안하다)'},
{id:'v012', w:'draft', pos:'n', mean:'초안', theme:'office', parts:[6,7], lv:2,
 ex:'Send me a rough draft before you finalize the report.', exK:'보고서를 확정하기 전에 초안을 보내 주세요.',
 col:'a rough draft 대략적인 초안 / draft a contract 계약서를 작성하다', syn:'outline, preliminary version', conf:'drift(n. 이동, 표류)'},
{id:'v013', w:'photocopier', pos:'n', mean:'복사기', theme:'office', parts:[1,3], lv:1,
 ex:'The photocopier on the second floor is out of order.', exK:'2층 복사기가 고장 났습니다.',
 col:'out of order 고장 난', syn:'copier, copy machine', conf:'photograph(n. 사진)'},
{id:'v014', w:'stationery', pos:'n', mean:'문구류, 사무용품', theme:'office', parts:[3,7], lv:2,
 ex:'Stationery supplies are kept in the cabinet by the printer.', exK:'문구류는 프린터 옆 캐비닛에 보관됩니다.',
 col:'order stationery 문구류를 주문하다', syn:'office supplies', conf:'stationary(a. 정지한) — 시험에 자주 나오는 짝입니다'},
{id:'v015', w:'extension', pos:'n', mean:'내선번호, 연장', theme:'office', parts:[4,7], lv:2,
 ex:'You can reach the help desk at extension 244.', exK:'헬프데스크는 내선 244번으로 연락하면 됩니다.',
 col:'request an extension 기한 연장을 요청하다', syn:'(기한) postponement', conf:'extent(n. 정도, 범위)'},
{id:'v016', w:'deadline', pos:'n', mean:'기한, 마감일', theme:'office', parts:[3,6,7], lv:1,
 ex:'We moved the deadline up by two days.', exK:'기한을 이틀 앞당겼습니다.',
 col:'meet a deadline 기한을 맞추다 / miss a deadline 기한을 놓치다', syn:'due date, cutoff', conf:'move up(앞당기다) / push back(미루다)'},
{id:'v017', w:'in charge of', pos:'phr', mean:'~을 담당하는', theme:'office', parts:[3,4,7], lv:1,
 ex:'Ms. Delgado is in charge of the training program.', exK:'Delgado 씨가 교육 프로그램을 담당합니다.',
 col:'be in charge of ~', syn:'responsible for, oversee', conf:'free of charge(무료로) — charge 의 뜻이 다릅니다'},
{id:'v018', w:'temporarily', pos:'ad', mean:'일시적으로', theme:'office', parts:[4,5,7], lv:2,
 ex:'The elevator is temporarily unavailable due to repairs.', exK:'수리 때문에 엘리베이터를 일시적으로 이용할 수 없습니다.',
 col:'temporarily closed 일시 휴업', syn:'for the time being', conf:'temporary(a. 일시적인) / contemporary(a. 현대의)'},

/* ======================= 인사 · 채용 (Personnel) ======================= */
{id:'v019', w:'applicant', pos:'n', mean:'지원자', theme:'hr', parts:[5,7], lv:1,
 ex:'Applicants must submit two letters of reference.', exK:'지원자는 추천서 두 통을 제출해야 합니다.',
 col:'a qualified applicant 자격을 갖춘 지원자', syn:'candidate', conf:'application(n. 지원서) / applicable(a. 적용되는)'},
{id:'v020', w:'résumé', pos:'n', mean:'이력서', theme:'hr', parts:[6,7], lv:1,
 ex:'Send your résumé and a cover letter to the address below.', exK:'이력서와 자기소개서를 아래 주소로 보내 주세요.',
 col:'update a résumé 이력서를 갱신하다', syn:'CV', conf:'resume(v. 재개하다) — 강세와 뜻이 다릅니다'},
{id:'v021', w:'recruit', pos:'v', mean:'채용하다, 모집하다', theme:'hr', parts:[5,7], lv:2,
 ex:'The firm is recruiting engineers for its overseas branch.', exK:'그 회사는 해외 지점 엔지니어를 모집하고 있습니다.',
 col:'recruit new staff 신규 직원을 채용하다', syn:'hire, take on', conf:'recruitment(n. 채용)'},
{id:'v022', w:'candidate', pos:'n', mean:'후보자, 지원자', theme:'hr', parts:[4,7], lv:1,
 ex:'The selected candidate will begin work on May 9.', exK:'선발된 지원자는 5월 9일에 근무를 시작합니다.',
 col:'a promising candidate 유망한 후보', syn:'applicant', conf:'candid(a. 솔직한)'},
{id:'v023', w:'promotion', pos:'n', mean:'승진, 판촉', theme:'hr', parts:[5,7], lv:2,
 ex:'She received a promotion after only two years.', exK:'그는 단 2년 만에 승진했습니다.',
 col:'earn a promotion 승진하다 / a promotional event 판촉 행사', syn:'advancement', conf:'문맥에 따라 승진/판촉으로 갈립니다'},
{id:'v024', w:'compensation', pos:'n', mean:'보수, 보상', theme:'hr', parts:[5,7], lv:2,
 ex:'The compensation package includes health insurance.', exK:'보수 패키지에는 건강보험이 포함됩니다.',
 col:'a compensation package 보수 조건', syn:'pay, remuneration', conf:'compensate for(~을 보상하다) — 전치사 for'},
{id:'v025', w:'benefits', pos:'n', mean:'복리후생', theme:'hr', parts:[6,7], lv:1,
 ex:'Full-time employees are eligible for benefits.', exK:'정규직 직원은 복리후생 대상입니다.',
 col:'employee benefits 직원 복리후생', syn:'perks', conf:'beneficial(a. 유익한)'},
{id:'v026', w:'eligible', pos:'a', mean:'자격이 있는', theme:'hr', parts:[5,6,7], lv:2,
 ex:'Only members are eligible to enter the contest.', exK:'회원만 대회에 참가할 자격이 있습니다.',
 col:'be eligible for + 명사 / be eligible to + 동사원형', syn:'qualified, entitled', conf:'illegible(a. 읽기 어려운) — 철자가 비슷합니다'},
{id:'v027', w:'supervisor', pos:'n', mean:'상사, 관리자', theme:'hr', parts:[3,4,7], lv:1,
 ex:'Report any safety concerns to your supervisor.', exK:'안전 문제는 상사에게 보고하세요.',
 col:'report to a supervisor 상사에게 보고하다', syn:'manager, superior', conf:'supervise(v. 감독하다) / oversee(v. 감독하다)'},
{id:'v028', w:'personnel', pos:'n', mean:'직원, 인사부', theme:'hr', parts:[6,7], lv:2,
 ex:'Access to the lab is limited to authorized personnel.', exK:'실험실 출입은 허가된 직원으로 제한됩니다.',
 col:'authorized personnel 허가된 직원', syn:'staff, employees', conf:'personal(a. 개인의) — 시험 단골 짝입니다'},
{id:'v029', w:'retirement', pos:'n', mean:'은퇴, 퇴직', theme:'hr', parts:[4,7], lv:2,
 ex:'A reception will be held to mark his retirement.', exK:'그의 퇴직을 기념해 축하연이 열립니다.',
 col:'announce one\'s retirement 은퇴를 발표하다', syn:'departure', conf:'retire(v. 은퇴하다) / retiree(n. 은퇴자)'},
{id:'v030', w:'evaluation', pos:'n', mean:'평가', theme:'hr', parts:[4,6,7], lv:2,
 ex:'Annual performance evaluations begin next month.', exK:'연간 성과 평가가 다음 달에 시작됩니다.',
 col:'a performance evaluation 성과 평가', syn:'assessment, appraisal, review', conf:'evaluate(v. 평가하다)'},
{id:'v031', w:'mandatory', pos:'a', mean:'의무적인, 필수의', theme:'hr', parts:[5,6,7], lv:2,
 ex:'Attendance at the orientation is mandatory.', exK:'오리엔테이션 참석은 의무입니다.',
 col:'mandatory training 필수 교육', syn:'required, compulsory, obligatory', conf:'voluntary(a. 자발적인) / optional(a. 선택의)'},
{id:'v032', w:'shift', pos:'n', mean:'근무 교대, 교대 시간', theme:'hr', parts:[3,4,7], lv:1,
 ex:'Please arrive ten minutes before your shift begins.', exK:'근무 시작 10분 전에 도착해 주세요.',
 col:'work the night shift 야간 근무를 하다 / cover a shift 대신 근무하다', syn:'work period', conf:'동사 shift(v. 옮기다, 바뀌다)'},
{id:'v033', w:'vacancy', pos:'n', mean:'공석, 빈자리 / (호텔) 빈 객실', theme:'hr', parts:[6,7], lv:3,
 ex:'There is a vacancy in the accounting department.', exK:'회계부에 공석이 있습니다.',
 col:'fill a vacancy 공석을 채우다 / no vacancies 만실', syn:'opening, position / available room', conf:'채용 문맥에서는 「공석」, 숙박 문맥에서는 「빈 객실」로 갈립니다'},
{id:'v034', w:'reference', pos:'n', mean:'추천서, 참고', theme:'hr', parts:[6,7], lv:2,
 ex:'Please include the names of two professional references.', exK:'업무 관련 추천인 두 명의 이름을 포함해 주세요.',
 col:'a letter of reference 추천서 / for future reference 향후 참고를 위해', syn:'recommendation', conf:'refer to(~을 참조하다)'},
{id:'v035', w:'probation', pos:'n', mean:'수습 기간', theme:'hr', parts:[7], lv:3,
 ex:'New hires serve a three-month probation period.', exK:'신입 사원은 3개월 수습 기간을 거칩니다.',
 col:'a probation period 수습 기간', syn:'trial period', conf:'prohibition(n. 금지)'},
{id:'v036', w:'workforce', pos:'n', mean:'인력, 노동력', theme:'hr', parts:[6,7], lv:3,
 ex:'The company plans to expand its workforce by 15 percent.', exK:'회사는 인력을 15퍼센트 늘릴 계획입니다.',
 col:'expand the workforce 인력을 늘리다', syn:'staff, labor force', conf:'workplace(n. 직장, 일터)'},

/* ======================= 일반 비즈니스 (General Business) ======================= */
{id:'v037', w:'negotiate', pos:'v', mean:'협상하다', theme:'biz', parts:[4,5,7], lv:2,
 ex:'The two firms are negotiating a long-term contract.', exK:'두 회사는 장기 계약을 협상하고 있습니다.',
 col:'negotiate terms 조건을 협상하다', syn:'bargain, discuss terms', conf:'negotiation(n. 협상) / negotiable(a. 협상 가능한)'},
{id:'v038', w:'contract', pos:'n', mean:'계약, 계약서', theme:'biz', parts:[5,6,7], lv:1,
 ex:'The contract expires at the end of the fiscal year.', exK:'계약은 회계연도 말에 만료됩니다.',
 col:'renew a contract 계약을 갱신하다 / breach of contract 계약 위반', syn:'agreement', conf:'contact(n. 연락, v. 연락하다) — 철자 한 글자 차이입니다'},
{id:'v039', w:'merger', pos:'n', mean:'합병', theme:'biz', parts:[6,7], lv:3,
 ex:'The board approved the merger with a rival firm.', exK:'이사회는 경쟁사와의 합병을 승인했습니다.',
 col:'a merger and acquisition 인수합병', syn:'consolidation', conf:'merge(v. 합병하다) / manager(n. 관리자)'},
{id:'v040', w:'warranty', pos:'n', mean:'품질 보증(서)', theme:'biz', parts:[6,7], lv:2,
 ex:'The printer comes with a two-year warranty.', exK:'그 프린터에는 2년 보증이 딸려 있습니다.',
 col:'under warranty 보증 기간 중 / a warranty covers ~ 보증이 ~을 보장한다', syn:'guarantee', conf:'warrant(v. 정당화하다, n. 영장)'},
{id:'v041', w:'revenue', pos:'n', mean:'수익, 매출', theme:'biz', parts:[6,7], lv:2,
 ex:'Advertising revenue rose sharply in the third quarter.', exK:'3분기에 광고 매출이 급증했습니다.',
 col:'generate revenue 수익을 창출하다', syn:'income, earnings, sales', conf:'revenue(총매출) ≠ profit(순이익)'},
{id:'v042', w:'launch', pos:'v', mean:'출시하다, 시작하다', theme:'biz', parts:[4,5,7], lv:1,
 ex:'The company will launch its new line this fall.', exK:'회사는 올가을 신제품 라인을 출시할 예정입니다.',
 col:'launch a campaign 캠페인을 시작하다 / a product launch 제품 출시', syn:'introduce, release, roll out', conf:'lunch(n. 점심)'},
{id:'v043', w:'expand', pos:'v', mean:'확장하다', theme:'biz', parts:[5,6,7], lv:1,
 ex:'They expanded their overseas offices from three to eleven.', exK:'해외 지점을 3개에서 11개로 확장했습니다.',
 col:'expand into a market 시장에 진출하다', syn:'grow, broaden, extend', conf:'expend(v. 소비하다) / expansion(n. 확장)'},
{id:'v044', w:'competitive', pos:'a', mean:'경쟁력 있는, 경쟁이 치열한', theme:'biz', parts:[5,6,7], lv:2,
 ex:'We offer competitive prices on all bulk orders.', exK:'모든 대량 주문에 경쟁력 있는 가격을 제공합니다.',
 col:'a competitive price 경쟁력 있는 가격 / a competitive edge 경쟁 우위', syn:'reasonable, attractive', conf:'competent(a. 유능한) / competitor(n. 경쟁자)'},
{id:'v045', w:'strategy', pos:'n', mean:'전략', theme:'biz', parts:[4,6,7], lv:2,
 ex:'The marketing strategy focuses on younger consumers.', exK:'마케팅 전략은 젊은 소비자에 집중합니다.',
 col:'implement a strategy 전략을 실행하다', syn:'plan, approach', conf:'strategic(a. 전략적인)'},
{id:'v046', w:'client', pos:'n', mean:'고객, 의뢰인', theme:'biz', parts:[3,4,7], lv:1,
 ex:'All client records will be moved to the new database.', exK:'모든 고객 기록은 새 데이터베이스로 이전됩니다.',
 col:'a potential client 잠재 고객 / retain a client 고객을 유지하다', syn:'customer, account', conf:'clientele(n. 고객층)'},
{id:'v047', w:'proposal', pos:'n', mean:'제안(서)', theme:'biz', parts:[3,6,7], lv:1,
 ex:'The client asked for a lower price in response to our proposal.', exK:'고객은 우리 제안에 대해 더 낮은 가격을 요구했습니다.',
 col:'submit a proposal 제안서를 제출하다 / accept a proposal 제안을 수락하다', syn:'offer, bid', conf:'propose(v. 제안하다) / purpose(n. 목적)'},
{id:'v048', w:'anticipate', pos:'v', mean:'예상하다', theme:'biz', parts:[5,6,7], lv:3,
 ex:'Sales are anticipated to double within two years.', exK:'매출은 2년 안에 두 배가 될 것으로 예상됩니다.',
 col:'anticipate demand 수요를 예상하다', syn:'expect, project, forecast', conf:'participate(v. 참가하다)'},
{id:'v049', w:'exceed', pos:'v', mean:'넘어서다, 초과하다', theme:'biz', parts:[5,6,7], lv:2,
 ex:'Third-quarter figures exceeded our forecast by ten percent.', exK:'3분기 실적은 예상치를 10퍼센트 넘어섰습니다.',
 col:'exceed expectations 기대를 뛰어넘다', syn:'surpass, go beyond', conf:'excel(v. 뛰어나다) / exceedingly(ad. 매우)'},
{id:'v050', w:'comply', pos:'v', mean:'준수하다, 따르다', theme:'biz', parts:[5,6,7], lv:3,
 ex:'All suppliers must comply with the new safety standards.', exK:'모든 공급업체는 새 안전 기준을 준수해야 합니다.',
 col:'comply with ~ (전치사 with 고정)', syn:'follow, adhere to, abide by', conf:'compile(v. 편집하다) / compliance(n. 준수)'},
{id:'v051', w:'endorse', pos:'v', mean:'지지하다, (제품을) 보증하다', theme:'biz', parts:[6,7], lv:3,
 ex:'A well-known chef endorsed the new line of cookware.', exK:'유명 요리사가 새 조리기구 제품군을 보증했습니다.',
 col:'endorse a product 제품을 홍보·보증하다', syn:'support, back, approve', conf:'endorsement(n. 보증, 지지)'},
{id:'v052', w:'on behalf of', pos:'phr', mean:'~을 대신하여, ~를 대표하여', theme:'biz', parts:[4,6,7], lv:2,
 ex:'On behalf of the entire team, thank you for your support.', exK:'팀 전체를 대표하여 지원에 감사드립니다.',
 col:'speak on behalf of ~', syn:'representing, for', conf:'in behalf of 와 뜻이 겹치지만 시험에는 on behalf of 가 나옵니다'},

/* ======================= 재무 · 예산 (Finance and Budgeting) ======================= */
{id:'v053', w:'invoice', pos:'n', mean:'청구서, 송장', theme:'fin', parts:[6,7], lv:1,
 ex:'Payment is due 30 days after the invoice date.', exK:'결제는 청구서 발행일로부터 30일 이내입니다.',
 col:'issue an invoice 청구서를 발행하다 / an outstanding invoice 미결제 청구서', syn:'bill, statement', conf:'invoice(청구서) / receipt(영수증)'},
{id:'v054', w:'reimburse', pos:'v', mean:'환급하다, 변제하다', theme:'fin', parts:[6,7], lv:3,
 ex:'The company will reimburse you for travel expenses.', exK:'회사가 출장 경비를 환급해 드립니다.',
 col:'reimburse + 사람 + for + 비용', syn:'refund, repay', conf:'reimbursement(n. 환급)'},
{id:'v055', w:'expense', pos:'n', mean:'비용, 경비', theme:'fin', parts:[5,6,7], lv:1,
 ex:'All receipts must be uploaded to the expense system.', exK:'모든 영수증은 경비 시스템에 올려야 합니다.',
 col:'cut expenses 비용을 줄이다 / at no additional expense 추가 비용 없이', syn:'cost, outlay', conf:'expensive(a. 비싼) / expend(v. 지출하다)'},
{id:'v056', w:'budget', pos:'n', mean:'예산', theme:'fin', parts:[3,4,6,7], lv:1,
 ex:'The project came in under budget.', exK:'그 사업은 예산보다 적게 들었습니다.',
 col:'stay within budget 예산 안에서 해결하다 / a tight budget 빡빡한 예산', syn:'financial plan, allocation', conf:'형용사로도 씁니다 — budget airline(저가 항공사)'},
{id:'v057', w:'audit', pos:'n', mean:'회계 감사', theme:'fin', parts:[6,7], lv:3,
 ex:'The auditors will arrive on Monday to begin the annual audit.', exK:'감사인들이 월요일에 와서 연간 감사를 시작합니다.',
 col:'conduct an audit 감사를 실시하다', syn:'inspection, examination', conf:'auditor(n. 감사인) / audience(n. 청중)'},
{id:'v058', w:'deposit', pos:'n', mean:'보증금, 예금', theme:'fin', parts:[3,7], lv:1,
 ex:'A refundable deposit of $200 is required at booking.', exK:'예약 시 환불 가능한 보증금 200달러가 필요합니다.',
 col:'a refundable deposit 환불 가능한 보증금 / make a deposit 입금하다', syn:'down payment, advance', conf:'withdrawal(n. 출금)'},
{id:'v059', w:'installment', pos:'n', mean:'분할 납입금', theme:'fin', parts:[7], lv:3,
 ex:'You may pay in twelve monthly installments.', exK:'12개월 분할로 납부할 수 있습니다.',
 col:'pay in installments 분할로 납부하다', syn:'partial payment', conf:'installation(n. 설치)'},
{id:'v060', w:'outstanding', pos:'a', mean:'미결제의 / 뛰어난', theme:'fin', parts:[5,6,7], lv:3,
 ex:'Please settle the outstanding balance by the end of the month.', exK:'미결제 잔액을 이달 말까지 정산해 주세요.',
 col:'an outstanding balance 미결제 잔액 / outstanding performance 뛰어난 성과', syn:'(미결제) unpaid, overdue / (뛰어난) excellent', conf:'문맥에 따라 뜻이 정반대처럼 갈립니다 — Part 7 함정'},
{id:'v061', w:'overdue', pos:'a', mean:'기한이 지난, 연체된', theme:'fin', parts:[6,7], lv:2,
 ex:'A late fee applies to overdue payments.', exK:'연체된 납입금에는 지연료가 부과됩니다.',
 col:'an overdue payment 연체금 / long overdue 오래 지연된', syn:'late, unpaid, outstanding', conf:'due(a. 예정된) / overdo(v. 지나치게 하다)'},
{id:'v062', w:'refund', pos:'n', mean:'환불', theme:'fin', parts:[3,6,7], lv:1,
 ex:'We will arrange a full refund if the schedule does not work.', exK:'일정이 맞지 않으면 전액 환불해 드립니다.',
 col:'a full refund 전액 환불 / issue a refund 환불해 주다', syn:'reimbursement, money back', conf:'refuse(v. 거절하다)'},
{id:'v063', w:'estimate', pos:'n', mean:'견적(서), 추정치', theme:'fin', parts:[3,6,7], lv:2,
 ex:'The contractor sent a written estimate for the repairs.', exK:'시공업체가 수리 견적서를 서면으로 보냈습니다.',
 col:'a written estimate 서면 견적 / a rough estimate 대략적인 추정', syn:'quote, quotation', conf:'estimated(a. 추정된) / estimation(n. 판단, 평가)'},
{id:'v064', w:'fiscal', pos:'a', mean:'회계의, 재정의', theme:'fin', parts:[6,7], lv:3,
 ex:'Results improved in the second half of the fiscal year.', exK:'회계연도 하반기에 실적이 개선되었습니다.',
 col:'the fiscal year 회계연도', syn:'financial', conf:'physical(a. 물리적인) — 발음이 비슷합니다'},
{id:'v065', w:'allocate', pos:'v', mean:'배정하다, 할당하다', theme:'fin', parts:[5,6,7], lv:3,
 ex:'More funds were allocated to research this year.', exK:'올해는 연구에 더 많은 자금이 배정되었습니다.',
 col:'allocate funds 자금을 배정하다', syn:'assign, distribute, earmark', conf:'locate(v. 위치를 찾다) / allocation(n. 배정)'},
{id:'v066', w:'due', pos:'a', mean:'예정된, 만기의', theme:'fin', parts:[5,6,7], lv:1,
 ex:'The final payment is due on the fifteenth.', exK:'최종 납입금은 15일이 기한입니다.',
 col:'be due on + 날짜 / due to + 명사(~때문에)', syn:'payable, scheduled', conf:'due to(전치사) 뒤에는 명사, because(접속사) 뒤에는 절이 옵니다'},

/* ======================= 구매 · 배송 (Purchasing) ======================= */
{id:'v067', w:'purchase', pos:'v', mean:'구매하다', theme:'purch', parts:[3,5,7], lv:1,
 ex:'Items purchased online can be returned in any store.', exK:'온라인에서 구매한 상품은 어느 매장에서든 반품할 수 있습니다.',
 col:'a proof of purchase 구매 증빙', syn:'buy, acquire', conf:'purchase(구매) / purchaser(구매자)'},
{id:'v068', w:'shipment', pos:'n', mean:'배송(품), 발송', theme:'purch', parts:[3,6,7], lv:1,
 ex:'The shipment was dispatched yesterday afternoon.', exK:'배송품은 어제 오후에 발송되었습니다.',
 col:'track a shipment 배송을 조회하다 / a delayed shipment 지연된 배송', syn:'delivery, consignment', conf:'ship(v. 발송하다) / shipping(n. 배송비, 운송)'},
{id:'v069', w:'inventory', pos:'n', mean:'재고, 재고 목록', theme:'purch', parts:[4,6,7], lv:2,
 ex:'We take inventory at the end of every month.', exK:'매월 말에 재고를 조사합니다.',
 col:'take inventory 재고를 조사하다 / out of stock 품절', syn:'stock, supplies', conf:'invention(n. 발명)'},
{id:'v070', w:'supplier', pos:'n', mean:'공급업체', theme:'purch', parts:[6,7], lv:1,
 ex:'Our supplier\'s warehouse was temporarily closed.', exK:'우리 공급업체의 창고가 일시적으로 문을 닫았습니다.',
 col:'a reliable supplier 믿을 만한 공급업체', syn:'vendor, provider', conf:'supply(n. 공급, v. 공급하다)'},
{id:'v071', w:'complimentary', pos:'a', mean:'무료의', theme:'purch', parts:[4,6,7], lv:3,
 ex:'Guests receive a complimentary breakfast.', exK:'투숙객은 무료 조식을 제공받습니다.',
 col:'a complimentary upgrade 무료 업그레이드', syn:'free, free of charge, on the house', conf:'complementary(a. 보완하는) — 철자 한 글자 차이의 단골 함정'},
{id:'v072', w:'defective', pos:'a', mean:'결함이 있는', theme:'purch', parts:[6,7], lv:2,
 ex:'Defective items may be exchanged within 14 days.', exK:'결함이 있는 상품은 14일 이내에 교환할 수 있습니다.',
 col:'a defective product 불량품', syn:'faulty, damaged, flawed', conf:'defect(n. 결함) / detective(n. 형사)'},
{id:'v073', w:'in stock', pos:'phr', mean:'재고가 있는', theme:'purch', parts:[3,7], lv:1,
 ex:'That model is no longer in stock.', exK:'그 모델은 더 이상 재고가 없습니다.',
 col:'in stock / out of stock / back in stock 재입고', syn:'available', conf:'in store(가게 안에) 와 다릅니다'},
{id:'v074', w:'bulk', pos:'n', mean:'대량', theme:'purch', parts:[6,7], lv:3,
 ex:'A discount applies to bulk orders of 100 units or more.', exK:'100개 이상 대량 주문에는 할인이 적용됩니다.',
 col:'in bulk 대량으로 / a bulk order 대량 주문', syn:'large quantity', conf:'bulky(a. 부피가 큰)'},
{id:'v075', w:'courier', pos:'n', mean:'택배(사), 특송', theme:'purch', parts:[3,7], lv:2,
 ex:'The documents were sent by express courier.', exK:'서류는 특송으로 발송되었습니다.',
 col:'by courier 택배로', syn:'delivery service', conf:'career(n. 경력) — 발음이 비슷합니다'},
{id:'v076', w:'itemize', pos:'v', mean:'항목별로 적다', theme:'purch', parts:[7], lv:3,
 ex:'Please submit an itemized receipt with your claim.', exK:'청구 시 항목별 영수증을 함께 제출해 주세요.',
 col:'an itemized bill 항목별 청구서', syn:'list in detail, break down', conf:'item(n. 항목, 물품)'},

/* ======================= 출장 · 여행 (Travel) ======================= */
{id:'v077', w:'itinerary', pos:'n', mean:'여행 일정표', theme:'travel', parts:[4,6,7], lv:3,
 ex:'A detailed itinerary will be e-mailed before departure.', exK:'출발 전에 상세 일정표를 이메일로 보내 드립니다.',
 col:'a revised itinerary 변경된 일정표', syn:'schedule, travel plan', conf:'interior(n. 내부)'},
{id:'v078', w:'accommodate', pos:'v', mean:'수용하다, 숙박시키다, 편의를 제공하다', theme:'travel', parts:[5,6,7], lv:3,
 ex:'The hall can accommodate up to 300 guests.', exK:'그 홀은 손님 300명까지 수용할 수 있습니다.',
 col:'accommodate a request 요청을 받아들이다', syn:'hold, house, seat', conf:'accommodation(n. 숙소) — 철자에 m 이 두 개입니다'},
{id:'v079', w:'depart', pos:'v', mean:'출발하다', theme:'travel', parts:[3,4,7], lv:1,
 ex:'The shuttle departs from the north entrance every hour.', exK:'셔틀은 매시간 북쪽 입구에서 출발합니다.',
 col:'depart from + 장소 / a departure time 출발 시각', syn:'leave, set off', conf:'department(n. 부서) — 철자가 겹칩니다'},
{id:'v080', w:'boarding pass', pos:'n', mean:'탑승권', theme:'travel', parts:[1,4], lv:1,
 ex:'Please have your boarding pass ready at the gate.', exK:'게이트에서 탑승권을 준비해 주세요.',
 col:'print a boarding pass 탑승권을 출력하다', syn:'ticket', conf:'board(v. 탑승하다) / aboard(ad. 탑승한)'},
{id:'v081', w:'layover', pos:'n', mean:'경유, 도중 체류', theme:'travel', parts:[3,4], lv:3,
 ex:'We have a two-hour layover in Frankfurt.', exK:'프랑크푸르트에서 두 시간 경유합니다.',
 col:'a short layover 짧은 경유', syn:'stopover, connection', conf:'leftover(n. 남은 것)'},
{id:'v082', w:'reservation', pos:'n', mean:'예약', theme:'travel', parts:[3,4,7], lv:1,
 ex:'Changes to the reservation must be made seven days in advance.', exK:'예약 변경은 7일 전에 해야 합니다.',
 col:'make a reservation 예약하다 / cancel a reservation 예약을 취소하다', syn:'booking', conf:'reserve(v. 예약하다) / reserved(a. 예약된)'},
{id:'v083', w:'fully booked', pos:'phr', mean:'예약이 다 찬, 만실인', theme:'travel', parts:[3,7], lv:2,
 ex:'The afternoon flight is fully booked.', exK:'오후 항공편은 예약이 다 찼습니다.',
 col:'fully booked 만석·만실 / no vacancies 만실', syn:'sold out, no seats left', conf:'overbooked(a. 초과 예약된)'},
{id:'v084', w:'delay', pos:'n', mean:'지연', theme:'travel', parts:[3,4,7], lv:1,
 ex:'Drivers are reporting delays of about twenty minutes.', exK:'운전자들이 약 20분 지연을 보고하고 있습니다.',
 col:'without delay 지체 없이 / a slight delay 약간의 지연', syn:'holdup, setback', conf:'delayed(a. 지연된) / delaying(a. 지연시키는)'},
{id:'v085', w:'detour', pos:'n', mean:'우회로', theme:'travel', parts:[4,7], lv:3,
 ex:'A detour is in place while the bridge is repaired.', exK:'교량 수리 중에는 우회로가 운영됩니다.',
 col:'take a detour 우회하다', syn:'alternate route', conf:'tour(n. 관광)'},
{id:'v086', w:'in advance', pos:'phr', mean:'미리, 사전에', theme:'travel', parts:[4,5,7], lv:1,
 ex:'Vacation requests must be submitted two weeks in advance.', exK:'휴가 신청은 2주 전에 제출해야 합니다.',
 col:'book in advance 미리 예약하다', syn:'beforehand, ahead of time', conf:'in advance of(~보다 앞서)'},
{id:'v087', w:'valid', pos:'a', mean:'유효한', theme:'travel', parts:[6,7], lv:2,
 ex:'The coupon is valid through December 31.', exK:'그 쿠폰은 12월 31일까지 유효합니다.',
 col:'a valid passport 유효한 여권 / valid through ~까지 유효', syn:'good, effective', conf:'invalid(a. 무효한) / validate(v. 확인하다)'},

/* ======================= 제조 · 생산 (Manufacturing) ======================= */
{id:'v088', w:'assembly line', pos:'n', mean:'조립 라인', theme:'manu', parts:[1,4,7], lv:2,
 ex:'Production on the assembly line stopped for two hours.', exK:'조립 라인 생산이 두 시간 동안 중단되었습니다.',
 col:'on the assembly line 조립 라인에서', syn:'production line', conf:'assembly(n. 조립, 집회) / assemble(v. 조립하다, 모이다)'},
{id:'v089', w:'facility', pos:'n', mean:'시설, 설비', theme:'manu', parts:[4,6,7], lv:2,
 ex:'The newly renovated facility includes a heated pool.', exK:'새로 개조된 시설에는 온수 수영장이 있습니다.',
 col:'a manufacturing facility 생산 시설 / facility tour 시설 견학', syn:'plant, building, premises', conf:'faculty(n. 교수진, 능력)'},
{id:'v090', w:'malfunction', pos:'v', mean:'제대로 작동하지 않다', theme:'manu', parts:[3,4,7], lv:3,
 ex:'The conveyor belt malfunctioned during the night shift.', exK:'야간 근무 중 컨베이어 벨트가 오작동했습니다.',
 col:'a malfunctioning machine 고장 난 기계', syn:'break down, fail', conf:'function(v. 작동하다) / dysfunction(n. 기능 장애)'},
{id:'v091', w:'quality control', pos:'n', mean:'품질 관리', theme:'manu', parts:[4,7], lv:2,
 ex:'Every unit passes through quality control before shipping.', exK:'모든 제품은 출하 전에 품질 관리를 거칩니다.',
 col:'a quality control inspection 품질 검사', syn:'QC, quality assurance', conf:'control quality 처럼 어순을 바꾸면 뜻이 달라집니다'},
{id:'v092', w:'inspect', pos:'v', mean:'점검하다, 검사하다', theme:'manu', parts:[4,5,7], lv:2,
 ex:'All safety equipment is inspected before the shift begins.', exK:'모든 안전 장비는 근무 시작 전에 점검됩니다.',
 col:'inspect for defects 결함을 점검하다', syn:'examine, check, review', conf:'inspection(n. 점검) / inspector(n. 검사관) / suspect(v. 의심하다)'},
{id:'v093', w:'output', pos:'n', mean:'생산량, 산출', theme:'manu', parts:[6,7], lv:2,
 ex:'The new machine has a much faster output speed.', exK:'새 기계는 산출 속도가 훨씬 빠릅니다.',
 col:'increase output 생산량을 늘리다', syn:'production, yield', conf:'input(n. 투입) / outlet(n. 매장, 콘센트)'},
{id:'v094', w:'streamline', pos:'v', mean:'간소화하다, 효율화하다', theme:'manu', parts:[6,7], lv:3,
 ex:'The new software streamlines the approval process.', exK:'새 소프트웨어는 승인 절차를 간소화합니다.',
 col:'streamline operations 운영을 효율화하다', syn:'simplify, optimize', conf:'stream(n. 흐름)'},
{id:'v095', w:'capacity', pos:'n', mean:'수용력, 생산 능력', theme:'manu', parts:[6,7], lv:2,
 ex:'The hall has a seating capacity of 120.', exK:'그 홀의 좌석 수용력은 120석입니다.',
 col:'at full capacity 최대 가동으로 / seating capacity 좌석 수', syn:'volume, ability', conf:'capability(n. 역량)'},

/* ======================= 기술 · IT (Technical Areas) ======================= */
{id:'v096', w:'install', pos:'v', mean:'설치하다', theme:'tech', parts:[3,4,7], lv:1,
 ex:'You will have time to install the app on your own phone.', exK:'각자 휴대전화에 앱을 설치할 시간이 있습니다.',
 col:'install software 소프트웨어를 설치하다', syn:'set up, put in', conf:'installation(n. 설치) / installment(n. 분할금)'},
{id:'v097', w:'upgrade', pos:'v', mean:'업그레이드하다, 개선하다', theme:'tech', parts:[6,7], lv:1,
 ex:'We have upgraded your shipping to express at no cost.', exK:'배송을 무료로 특급으로 업그레이드했습니다.',
 col:'upgrade a system 시스템을 업그레이드하다', syn:'improve, enhance', conf:'downgrade(v. 등급을 낮추다)'},
{id:'v098', w:'troubleshoot', pos:'v', mean:'문제를 해결하다', theme:'tech', parts:[4,7], lv:3,
 ex:'The technician troubleshot the network issue in an hour.', exK:'기술자가 한 시간 만에 네트워크 문제를 해결했습니다.',
 col:'a troubleshooting guide 문제 해결 안내서', syn:'resolve, fix, diagnose', conf:'trouble(n. 문제)'},
{id:'v099', w:'compatible', pos:'a', mean:'호환되는', theme:'tech', parts:[6,7], lv:3,
 ex:'The adapter is compatible with all recent models.', exK:'그 어댑터는 최신 모델 전부와 호환됩니다.',
 col:'be compatible with ~ (전치사 with)', syn:'suitable for, works with', conf:'comparable(a. 비교할 만한)'},
{id:'v100', w:'automatically', pos:'ad', mean:'자동으로', theme:'tech', parts:[4,5,7], lv:1,
 ex:'The app will automatically match each receipt to your statement.', exK:'앱이 각 영수증을 명세서와 자동으로 대조합니다.',
 col:'be updated automatically 자동으로 갱신되다', syn:'by itself, without input', conf:'automatic(a. 자동의) / automation(n. 자동화)'},
{id:'v101', w:'access', pos:'n', mean:'접근, 이용 권한', theme:'tech', parts:[5,6,7], lv:2,
 ex:'Access to the server room is restricted to authorized staff.', exK:'서버실 출입은 허가된 직원으로 제한됩니다.',
 col:'have access to ~ / gain access 접근 권한을 얻다', syn:'entry, admission', conf:'assess(v. 평가하다) / excess(n. 초과)'},
{id:'v102', w:'back up', pos:'phr', mean:'백업하다', theme:'tech', parts:[4,7], lv:2,
 ex:'Be sure to back up your files before the update.', exK:'업데이트 전에 파일을 반드시 백업하세요.',
 col:'back up data 데이터를 백업하다', syn:'save a copy', conf:'명사는 backup(백업본)으로 붙여 씁니다'},
{id:'v103', w:'specification', pos:'n', mean:'명세, 규격', theme:'tech', parts:[6,7], lv:3,
 ex:'The parts were made to the customer\'s specifications.', exK:'부품은 고객 규격에 맞춰 제작되었습니다.',
 col:'technical specifications 기술 규격', syn:'requirements, details', conf:'specific(a. 구체적인) / specify(v. 명시하다)'},
{id:'v104', w:'implement', pos:'v', mean:'실행하다, 도입하다', theme:'tech', parts:[5,6,7], lv:3,
 ex:'The recommendations were practical and easy to implement.', exK:'그 권고안은 실용적이고 실행하기 쉬웠습니다.',
 col:'implement a policy 정책을 시행하다', syn:'carry out, execute, put into practice', conf:'implementation(n. 실행) / complement(v. 보완하다)'},

/* ======================= 주택 · 부동산 (Housing / Corporate Property) ======================= */
{id:'v105', w:'lease', pos:'n', mean:'임대차 계약', theme:'house', parts:[6,7], lv:2,
 ex:'The lease expires at the end of August.', exK:'임대차 계약은 8월 말에 만료됩니다.',
 col:'renew a lease 임대 계약을 갱신하다 / sign a lease 임대 계약을 체결하다', syn:'rental agreement', conf:'least(a. 가장 적은) — 발음이 비슷합니다'},
{id:'v106', w:'tenant', pos:'n', mean:'세입자, 임차인', theme:'house', parts:[6,7], lv:2,
 ex:'Tenants must give 30 days\' notice before moving out.', exK:'세입자는 퇴거 30일 전에 통지해야 합니다.',
 col:'a commercial tenant 상업 임차인', syn:'renter, occupant', conf:'landlord(n. 임대인)'},
{id:'v107', w:'renovate', pos:'v', mean:'개조하다, 보수하다', theme:'house', parts:[4,6,7], lv:2,
 ex:'The lobby will be renovated over the summer.', exK:'로비는 여름 동안 개조될 예정입니다.',
 col:'a newly renovated facility 새로 개조된 시설', syn:'remodel, refurbish, upgrade', conf:'renovation(n. 개조) / innovate(v. 혁신하다)'},
{id:'v108', w:'premises', pos:'n', mean:'건물, 부지, 구내', theme:'house', parts:[6,7], lv:3,
 ex:'Smoking is not permitted anywhere on the premises.', exK:'구내 어디에서도 흡연은 허용되지 않습니다.',
 col:'on the premises 구내에서', syn:'grounds, property, site', conf:'promise(n. 약속) — 철자가 비슷합니다'},
{id:'v109', w:'resurface', pos:'v', mean:'(노면을) 재포장하다', theme:'house', parts:[6,7], lv:3,
 ex:'The north parking lot will be resurfaced next week.', exK:'북쪽 주차장은 다음 주에 재포장됩니다.',
 col:'resurface a road 도로를 재포장하다', syn:'repave', conf:'surface(n. 표면)'},
{id:'v110', w:'utility', pos:'n', mean:'공공요금, 공공설비', theme:'house', parts:[6,7], lv:3,
 ex:'Rent includes water but not other utilities.', exK:'임대료에는 수도가 포함되지만 다른 공공요금은 제외입니다.',
 col:'utility bills 공공요금 청구서', syn:'services (gas, electricity, water)', conf:'utilize(v. 활용하다) / utensil(n. 기구)'},
{id:'v111', w:'occupancy', pos:'n', mean:'입주, 사용, 점유', theme:'house', parts:[7], lv:3,
 ex:'The building is ready for occupancy in October.', exK:'그 건물은 10월에 입주가 가능합니다.',
 col:'maximum occupancy 최대 수용 인원', syn:'use, tenancy', conf:'occupation(n. 직업, 점령) / occupy(v. 차지하다)'},
{id:'v112', w:'maintenance', pos:'n', mean:'유지 보수, 관리', theme:'house', parts:[4,6,7], lv:1,
 ex:'All maintenance requests should be addressed to the supervisor.', exK:'모든 유지 보수 요청은 관리자에게 전달해야 합니다.',
 col:'routine maintenance 정기 점검 / under maintenance 점검 중', syn:'upkeep, servicing', conf:'maintain(v. 유지하다)'},

/* ======================= 기업 개발 (Corporate Development) ======================= */
{id:'v113', w:'prototype', pos:'n', mean:'시제품, 원형', theme:'corp', parts:[4,7], lv:3,
 ex:'The team will present a working prototype next month.', exK:'팀은 다음 달에 작동하는 시제품을 발표할 예정입니다.',
 col:'develop a prototype 시제품을 개발하다', syn:'model, sample', conf:'type(n. 유형)'},
{id:'v114', w:'patent', pos:'n', mean:'특허(권)', theme:'corp', parts:[6,7], lv:3,
 ex:'The firm holds a patent on the cooling technology.', exK:'그 회사는 냉각 기술에 대한 특허를 보유하고 있습니다.',
 col:'file for a patent 특허를 출원하다 / hold a patent 특허를 보유하다', syn:'exclusive right', conf:'patient(n. 환자, a. 인내심 있는)'},
{id:'v115', w:'feasible', pos:'a', mean:'실현 가능한', theme:'corp', parts:[6,7], lv:3,
 ex:'A second production site is not financially feasible this year.', exK:'두 번째 생산 시설은 올해 재정적으로 실현 가능하지 않습니다.',
 col:'a feasibility study 타당성 조사', syn:'possible, practical, viable', conf:'feeble(a. 약한)'},
{id:'v116', w:'innovative', pos:'a', mean:'혁신적인', theme:'corp', parts:[6,7], lv:2,
 ex:'The award recognizes innovative packaging design.', exK:'그 상은 혁신적인 포장 디자인을 인정하는 것입니다.',
 col:'an innovative approach 혁신적인 접근', syn:'creative, groundbreaking, novel', conf:'innovation(n. 혁신) / renovate(v. 개조하다)'},
{id:'v117', w:'collaborate', pos:'v', mean:'협업하다', theme:'corp', parts:[5,6,7], lv:2,
 ex:'The two departments collaborated closely on the launch.', exK:'두 부서는 출시를 두고 긴밀히 협업했습니다.',
 col:'collaborate with ~ / in close collaboration 긴밀한 협업으로', syn:'work together, cooperate, partner', conf:'collaboration(n. 협업) / corroborate(v. 입증하다)'},
{id:'v118', w:'milestone', pos:'n', mean:'중요한 단계, 이정표', theme:'corp', parts:[6,7], lv:3,
 ex:'Reaching one million users was a major milestone.', exK:'사용자 100만 명 달성은 중요한 이정표였습니다.',
 col:'reach a milestone 이정표에 도달하다', syn:'landmark, turning point', conf:'mileage(n. 주행 거리)'},

/* ======================= 식사 · 행사 (Dining Out) ======================= */
{id:'v119', w:'catering', pos:'n', mean:'출장 요리, 케이터링', theme:'dine', parts:[3,4,7], lv:2,
 ex:'Catering for the reception is included in the price.', exK:'가격에는 축하연 케이터링이 포함되어 있습니다.',
 col:'a catering service 케이터링 업체', syn:'food service', conf:'cater to(~의 요구를 맞추다)'},
{id:'v120', w:'reception', pos:'n', mean:'축하연, 접수처', theme:'dine', parts:[3,4,7], lv:1,
 ex:'A reception will follow the awards ceremony.', exK:'시상식 후에 축하연이 이어집니다.',
 col:'hold a reception 축하연을 열다 / at the reception desk 안내 데스크에서', syn:'party, banquet', conf:'receipt(n. 영수증) / recipient(n. 수령인)'},
{id:'v121', w:'beverage', pos:'n', mean:'음료', theme:'dine', parts:[1,3,7], lv:2,
 ex:'Light snacks and beverages will be served.', exK:'간단한 간식과 음료가 제공됩니다.',
 col:'complimentary beverages 무료 음료', syn:'drink, refreshment', conf:'leverage(n. 영향력)'},
{id:'v122', w:'reserve', pos:'v', mean:'예약하다, 따로 남겨 두다', theme:'dine', parts:[3,5,7], lv:1,
 ex:'Would you like me to reserve a table for lunch?', exK:'점심 식사 자리를 예약해 드릴까요?',
 col:'reserve a table 자리를 예약하다 / reserved for ~용으로 지정된', syn:'book, set aside', conf:'preserve(v. 보존하다) / deserve(v. ~할 만하다)'},
{id:'v123', w:'venue', pos:'n', mean:'장소, 개최지', theme:'dine', parts:[4,6,7], lv:3,
 ex:'The venue was changed to the conference center on Elm Street.', exK:'장소가 Elm 가의 컨벤션 센터로 변경되었습니다.',
 col:'change the venue 장소를 변경하다', syn:'location, site, place', conf:'avenue(n. 대로)'},
{id:'v124', w:'refreshments', pos:'n', mean:'간단한 다과', theme:'dine', parts:[4,7], lv:2,
 ex:'Refreshments are available in the lobby during the break.', exK:'휴식 시간에 로비에서 다과를 이용할 수 있습니다.',
 col:'serve refreshments 다과를 제공하다', syn:'snacks and drinks', conf:'refresh(v. 새롭게 하다)'},

/* ======================= 문화 · 여가 (Entertainment) ======================= */
{id:'v125', w:'exhibition', pos:'n', mean:'전시(회)', theme:'ent', parts:[4,7], lv:2,
 ex:'The exhibition runs through the end of the month.', exK:'전시는 이달 말까지 진행됩니다.',
 col:'hold an exhibition 전시를 열다 / on exhibit 전시 중', syn:'display, show', conf:'exhibit(v. 전시하다, n. 전시품) / inhibit(v. 억제하다)'},
{id:'v126', w:'admission', pos:'n', mean:'입장(료), 입학', theme:'ent', parts:[4,7], lv:2,
 ex:'Admission is free for members on weekdays.', exK:'평일에는 회원 입장이 무료입니다.',
 col:'admission fee 입장료 / free admission 무료 입장', syn:'entry, entrance', conf:'admit(v. 인정하다, 입장을 허가하다)'},
{id:'v127', w:'renowned', pos:'a', mean:'유명한, 명성 있는', theme:'ent', parts:[6,7], lv:3,
 ex:'A renowned pianist will perform at the opening.', exK:'유명 피아니스트가 개막 공연을 합니다.',
 col:'be renowned for ~로 유명하다', syn:'famous, prominent, noted, well-known', conf:'Part 7 에서 famous ↔ renowned 로 바꿔 나옵니다'},
{id:'v128', w:'sold out', pos:'phr', mean:'매진된', theme:'ent', parts:[3,4,7], lv:1,
 ex:'The evening performance is completely sold out.', exK:'저녁 공연은 완전히 매진되었습니다.',
 col:'sell out 매진되다', syn:'fully booked, no tickets left', conf:'sold-out(a. 매진된) — 형용사로 쓸 때 붙임표가 들어갑니다'},
{id:'v129', w:'feature', pos:'v', mean:'특징으로 하다, 주요하게 다루다', theme:'ent', parts:[4,6,7], lv:2,
 ex:'The gallery features works by local artists.', exK:'그 갤러리는 지역 예술가들의 작품을 주로 전시합니다.',
 col:'feature a guest speaker 초청 연사를 내세우다', syn:'include, highlight, showcase', conf:'명사 feature(특징, 기능)로도 자주 나옵니다'},
{id:'v130', w:'anniversary', pos:'n', mean:'기념일', theme:'ent', parts:[4,7], lv:2,
 ex:'The store is marking its tenth anniversary with a sale.', exK:'그 매장은 10주년을 세일로 기념하고 있습니다.',
 col:'mark an anniversary 기념일을 기리다', syn:'commemoration', conf:'annual(a. 연간의) / annually(ad. 매년)'},

/* ======================= 보건 · 의료 (Health) ======================= */
{id:'v131', w:'appointment', pos:'n', mean:'약속, 진료 예약', theme:'health', parts:[3,4,7], lv:1,
 ex:'You can reschedule your appointment online.', exK:'온라인으로 진료 예약을 변경할 수 있습니다.',
 col:'make an appointment 예약하다 / keep an appointment 약속을 지키다', syn:'booking, scheduled visit', conf:'appoint(v. 임명하다) — 「임명」의 뜻으로도 나옵니다'},
{id:'v132', w:'prescription', pos:'n', mean:'처방(전)', theme:'health', parts:[3,7], lv:2,
 ex:'Bring your prescription to the pharmacy on the first floor.', exK:'처방전을 1층 약국으로 가져가세요.',
 col:'fill a prescription 처방약을 조제받다', syn:'doctor\'s order', conf:'prescribe(v. 처방하다) / subscription(n. 구독)'},
{id:'v133', w:'coverage', pos:'n', mean:'보장 범위, 보도', theme:'health', parts:[6,7], lv:3,
 ex:'The plan provides dental coverage for dependents.', exK:'그 보험은 피부양자의 치과 보장을 제공합니다.',
 col:'insurance coverage 보험 보장 범위', syn:'protection, benefits', conf:'cover(v. 보장하다, 다루다)'},
{id:'v134', w:'physician', pos:'n', mean:'의사, 내과의', theme:'health', parts:[4,7], lv:3,
 ex:'Consult your physician before starting the program.', exK:'프로그램을 시작하기 전에 의사와 상의하세요.',
 col:'a family physician 주치의', syn:'doctor', conf:'physicist(n. 물리학자) / physical(a. 신체의)'},
{id:'v135', w:'symptom', pos:'n', mean:'증상', theme:'health', parts:[7], lv:2,
 ex:'Employees with flu symptoms should stay home.', exK:'독감 증상이 있는 직원은 집에 있어야 합니다.',
 col:'show symptoms 증상을 보이다', syn:'sign, indication', conf:'system(n. 체계)'},
{id:'v136', w:'checkup', pos:'n', mean:'건강 검진', theme:'health', parts:[3,7], lv:2,
 ex:'Annual checkups are covered by the company plan.', exK:'연간 건강 검진은 회사 보험으로 보장됩니다.',
 col:'have a checkup 검진을 받다', syn:'examination, physical', conf:'check up on(~을 확인하다)'},

/* ================================================================
   Part 7 패러프레이징 짝 — 지문 표현이 선택지에서 다른 말로 바뀝니다
   ================================================================ */
{id:'p001', w:'oversee', pos:'v', mean:'감독하다', theme:'office', parts:[7], lv:3,
 ex:'Ms. Han oversees the entire distribution network.', exK:'Han 씨가 유통망 전체를 감독합니다.',
 col:'oversee a project 프로젝트를 총괄하다', syn:'supervise, manage, be in charge of', conf:'overlook(v. 간과하다, 내려다보다) — 뜻이 전혀 다릅니다'},
{id:'p002', w:'eliminate', pos:'v', mean:'없애다, 제거하다', theme:'biz', parts:[5,7], lv:3,
 ex:'The new policy aims to eliminate unnecessary paperwork.', exK:'새 정책은 불필요한 서류 작업을 없애는 것을 목표로 합니다.',
 col:'eliminate waste 낭비를 없애다', syn:'remove, get rid of, do away with', conf:'illuminate(v. 밝히다)'},
{id:'p003', w:'undertake', pos:'v', mean:'착수하다, 맡다', theme:'corp', parts:[6,7], lv:3,
 ex:'The agency undertook a citywide survey last spring.', exK:'그 기관은 지난봄 시 전역 조사를 맡았습니다.',
 col:'undertake a study 연구에 착수하다', syn:'take on, assume, embark on', conf:'undergo(v. 겪다)'},
{id:'p004', w:'conduct', pos:'v', mean:'실시하다, 수행하다', theme:'corp', parts:[4,5,7], lv:2,
 ex:'The firm conducts customer surveys twice a year.', exK:'그 회사는 연 2회 고객 설문을 실시합니다.',
 col:'conduct research 연구를 수행하다 / conduct an interview 면접을 실시하다', syn:'carry out, perform, execute', conf:'명사 conduct(행동, 처신)로도 나옵니다'},
{id:'p005', w:'prominent', pos:'a', mean:'유명한, 두드러진', theme:'ent', parts:[6,7], lv:3,
 ex:'A prominent architect designed the new wing.', exK:'유명 건축가가 새 별관을 설계했습니다.',
 col:'a prominent figure 저명한 인물', syn:'well-known, renowned, leading, noted', conf:'permanent(a. 영구적인)'},
{id:'p006', w:'widespread', pos:'a', mean:'널리 퍼진', theme:'biz', parts:[6,7], lv:3,
 ex:'The app gained widespread popularity within months.', exK:'그 앱은 몇 달 안에 널리 인기를 얻었습니다.',
 col:'widespread use 광범위한 사용', syn:'prevalent, common, extensive', conf:'spread(v. 퍼지다)'},
{id:'p007', w:'assignment', pos:'n', mean:'과제, 업무', theme:'office', parts:[6,7], lv:2,
 ex:'She completed the assignment ahead of schedule.', exK:'그는 예정보다 앞서 과제를 마쳤습니다.',
 col:'a challenging assignment 어려운 업무', syn:'task, job, duty', conf:'assign(v. 배정하다) / assignee(n. 양수인)'},
{id:'p008', w:'outlook', pos:'n', mean:'전망', theme:'fin', parts:[6,7], lv:3,
 ex:'The economic outlook for next quarter is positive.', exK:'다음 분기 경제 전망은 긍정적입니다.',
 col:'a positive outlook 긍정적인 전망', syn:'prospect, forecast, projection', conf:'lookout(n. 감시, 경계)'},
{id:'p009', w:'sufficient', pos:'a', mean:'충분한', theme:'biz', parts:[5,6,7], lv:2,
 ex:'We do not have sufficient funds for a second site.', exK:'두 번째 시설을 위한 충분한 자금이 없습니다.',
 col:'sufficient time 충분한 시간', syn:'enough, adequate, ample', conf:'efficient(a. 효율적인) — 시험 단골 짝입니다'},
{id:'p010', w:'approximately', pos:'ad', mean:'대략, 약', theme:'biz', parts:[4,5,7], lv:2,
 ex:'The delivery will be delayed by approximately one week.', exK:'배송은 약 1주일 지연됩니다.',
 col:'approximately + 숫자', syn:'about, roughly, around, some', conf:'appropriately(ad. 적절하게)'},
{id:'p011', w:'promptly', pos:'ad', mean:'즉시, 정확히 (시간에)', theme:'office', parts:[4,5,7], lv:2,
 ex:'The session will begin promptly at nine.', exK:'회의는 9시 정각에 시작됩니다.',
 col:'respond promptly 즉시 응답하다', syn:'immediately, right away, at once', conf:'prompt(a. 신속한, v. 촉발하다)'},
{id:'p012', w:'subsequently', pos:'ad', mean:'그 후에, 이어서', theme:'office', parts:[6,7], lv:3,
 ex:'The proposal was reviewed and subsequently approved.', exK:'제안서는 검토를 거쳐 그 후 승인되었습니다.',
 col:'subsequently + 과거 동사', syn:'later, afterward, then', conf:'consequently(ad. 그 결과) — 뜻이 다릅니다'},
{id:'p013', w:'regarding', pos:'phr', mean:'~에 관하여', theme:'office', parts:[6,7], lv:2,
 ex:'I am writing regarding your order placed on March 2.', exK:'3월 2일 주문에 관해 연락드립니다.',
 col:'regarding + 명사', syn:'concerning, about, with regard to, in reference to', conf:'뒤에 절이 오면 쓸 수 없습니다'},
{id:'p014', w:'in the event of', pos:'phr', mean:'~의 경우에', theme:'biz', parts:[6,7], lv:3,
 ex:'In the event of cancellation, a full refund will be issued.', exK:'취소하는 경우 전액 환불됩니다.',
 col:'in the event of + 명사 / in the event that + 절', syn:'if, should ~ occur', conf:'in the event that 다음에는 절이 옵니다'},
{id:'p015', w:'be subject to', pos:'phr', mean:'~의 대상이다, ~에 따라 달라진다', theme:'biz', parts:[6,7], lv:3,
 ex:'Prices are subject to change without notice.', exK:'가격은 예고 없이 변경될 수 있습니다.',
 col:'be subject to approval 승인을 받아야 한다', syn:'liable to, dependent on', conf:'be subjected to(~을 당하다)와 뜻이 다릅니다'},
{id:'p016', w:'attribute', pos:'v', mean:'~의 원인으로 보다', theme:'fin', parts:[6,7], lv:3,
 ex:'The rise in sales was attributed to the new campaign.', exK:'매출 증가는 새 캠페인 덕으로 여겨졌습니다.',
 col:'attribute A to B', syn:'credit to, ascribe to', conf:'contribute(v. 기여하다) — attribute 는 원인, contribute 는 기여'},
{id:'p017', w:'expedite', pos:'v', mean:'신속히 처리하다', theme:'purch', parts:[7], lv:3,
 ex:'We can expedite your order for an extra fee.', exK:'추가 요금을 내면 주문을 신속히 처리할 수 있습니다.',
 col:'expedite the process 절차를 앞당기다', syn:'speed up, accelerate, rush', conf:'expedition(n. 원정, 탐험)'},
{id:'p018', w:'waive', pos:'v', mean:'면제하다, 철회하다', theme:'fin', parts:[7], lv:3,
 ex:'The registration fee will be waived for early sign-ups.', exK:'조기 등록자에게는 등록비가 면제됩니다.',
 col:'waive a fee 수수료를 면제하다', syn:'cancel, drop, forgo', conf:'wave(v. 손을 흔들다) — 발음이 같습니다'},
{id:'p019', w:'commence', pos:'v', mean:'시작하다', theme:'office', parts:[6,7], lv:3,
 ex:'Construction will commence in early April.', exK:'공사는 4월 초에 시작됩니다.',
 col:'commence operations 운영을 시작하다', syn:'begin, start, get under way', conf:'commend(v. 칭찬하다) / comment(v. 논평하다)'},
{id:'p020', w:'discontinue', pos:'v', mean:'중단하다, 단종하다', theme:'purch', parts:[6,7], lv:3,
 ex:'That model has been discontinued.', exK:'그 모델은 단종되었습니다.',
 col:'a discontinued item 단종 상품', syn:'stop, phase out, cease', conf:'continue(v. 계속하다) / continuous(a. 지속적인)'},

/* ================================================================
   혼동어휘 — 형태가 닮아 오답으로 깔리는 짝
   ================================================================ */
{id:'c001', w:'affect', pos:'v', mean:'영향을 주다', theme:'biz', parts:[5,7], lv:2,
 ex:'The delay will not affect the launch date.', exK:'그 지연은 출시일에 영향을 주지 않습니다.',
 col:'affect + 목적어 (전치사 없이)', syn:'influence, impact', conf:'effect(n. 영향) — affect 는 동사, effect 는 명사가 기본입니다'},
{id:'c002', w:'effective', pos:'a', mean:'효과적인 / (제도가) 시행되는', theme:'biz', parts:[5,6,7], lv:2,
 ex:'The new rate is effective as of June 1.', exK:'새 요율은 6월 1일부터 시행됩니다.',
 col:'effective immediately 즉시 시행 / an effective method 효과적인 방법', syn:'in force, valid / successful', conf:'efficient(a. 효율적인) — effective 는 효과, efficient 는 능률'},
{id:'c003', w:'considerable', pos:'a', mean:'상당한, 많은', theme:'fin', parts:[5,6,7], lv:3,
 ex:'The renovation required a considerable investment.', exK:'개조에는 상당한 투자가 필요했습니다.',
 col:'a considerable amount 상당한 양', syn:'substantial, significant', conf:'considerate(a. 배려하는) — 뜻이 완전히 다릅니다'},
{id:'c004', w:'respectively', pos:'ad', mean:'각각', theme:'fin', parts:[6,7], lv:3,
 ex:'Sales rose 8 and 12 percent, respectively.', exK:'매출은 각각 8퍼센트와 12퍼센트 올랐습니다.',
 col:'A and B, respectively', syn:'in that order', conf:'respectfully(ad. 정중하게) — 편지 맺음말에 쓰입니다'},
{id:'c005', w:'reliable', pos:'a', mean:'믿을 만한', theme:'purch', parts:[5,6,7], lv:2,
 ex:'We need a more reliable supplier for these parts.', exK:'이 부품에는 더 믿을 만한 공급업체가 필요합니다.',
 col:'a reliable source 믿을 만한 출처', syn:'dependable, trustworthy', conf:'reliant(a. 의존하는) — be reliant on ~'},
{id:'c006', w:'economical', pos:'a', mean:'경제적인, 알뜰한', theme:'fin', parts:[5,7], lv:3,
 ex:'Shipping by sea is more economical for bulk orders.', exK:'대량 주문에는 해상 운송이 더 경제적입니다.',
 col:'an economical option 경제적인 선택', syn:'cost-effective, inexpensive', conf:'economic(a. 경제의) — economic growth(경제 성장)와 구별하세요'},
{id:'c007', w:'successive', pos:'a', mean:'연속적인', theme:'biz', parts:[6,7], lv:3,
 ex:'Profits rose for the fifth successive quarter.', exK:'이익이 5분기 연속으로 올랐습니다.',
 col:'successive years 연속되는 해', syn:'consecutive, in a row', conf:'successful(a. 성공적인)'},
{id:'c008', w:'complementary', pos:'a', mean:'보완적인, 서로 보완하는', theme:'biz', parts:[5,7], lv:3,
 ex:'The two products have complementary features.', exK:'두 제품은 서로 보완적인 기능을 갖고 있습니다.',
 col:'complementary services 상호 보완적인 서비스', syn:'mutually supporting', conf:'complimentary(a. 무료의) — i 와 e 한 글자 차이로 뜻이 완전히 다릅니다'},
{id:'c009', w:'assure', pos:'v', mean:'(사람에게) 확언하다', theme:'office', parts:[5,7], lv:3,
 ex:'I assure you that the order will arrive on time.', exK:'주문이 정시에 도착할 것임을 확언드립니다.',
 col:'assure + 사람 + that절', syn:'reassure, promise', conf:'ensure(v. 확실히 하다 — that절), insure(v. 보험에 들다)'},
{id:'c010', w:'adapt', pos:'v', mean:'적응하다, 조정하다', theme:'corp', parts:[5,7], lv:3,
 ex:'The design was adapted for the overseas market.', exK:'디자인은 해외 시장에 맞게 조정되었습니다.',
 col:'adapt to a change 변화에 적응하다', syn:'adjust, modify, tailor', conf:'adopt(v. 채택하다) — 한 글자 차이로 뜻이 다릅니다'},
{id:'c011', w:'lay off', pos:'phr', mean:'해고하다, 일시 해고하다', theme:'hr', parts:[7], lv:3,
 ex:'The plant laid off thirty workers last winter.', exK:'그 공장은 지난겨울 노동자 30명을 해고했습니다.',
 col:'be laid off 해고되다', syn:'dismiss, let go', conf:'lie(눕다) / lay(놓다) 활용 혼동에 주의하세요'},
{id:'c012', w:'raise', pos:'n', mean:'임금 인상', theme:'hr', parts:[3,7], lv:2,
 ex:'All staff received a three percent raise.', exK:'전 직원이 3퍼센트 임금 인상을 받았습니다.',
 col:'get a raise 임금이 오르다', syn:'pay increase', conf:'rise(v. 오르다 — 자동사) / raise(v. 올리다 — 타동사)'}
];

/* ================================================================
   2차 추가 — Part 5·6 빈출 어휘 보강
   ================================================================ */
const TO_VOCA_SEED2 = [
{id:'v137', w:'approve', pos:'v', mean:'승인하다', theme:'office', parts:[4,5,7], lv:1,
 ex:'The board approved the merger last Tuesday.', exK:'이사회는 지난 화요일 합병을 승인했습니다.',
 col:'approve a request 요청을 승인하다 / approve of ~을 찬성하다', syn:'authorize, endorse, sign off on', conf:'approval(n. 승인) / prove(v. 증명하다)'},
{id:'v138', w:'authorize', pos:'v', mean:'권한을 주다, 인가하다', theme:'office', parts:[5,6,7], lv:2,
 ex:'Only managers are authorized to sign purchase orders.', exK:'관리자만 구매 주문서에 서명할 권한이 있습니다.',
 col:'authorized personnel 허가된 직원', syn:'permit, empower', conf:'author(n. 저자) / authority(n. 권한, 당국)'},
{id:'v139', w:'coordinate', pos:'v', mean:'조율하다, 조정하다', theme:'office', parts:[4,6,7], lv:2,
 ex:'Please coordinate with the design team on the layout.', exK:'배치는 디자인팀과 조율해 주세요.',
 col:'coordinate with ~ / a coordinator 담당자', syn:'organize, arrange, liaise with', conf:'cooperate(v. 협력하다)'},
{id:'v140', w:'delegate', pos:'v', mean:'위임하다', theme:'office', parts:[6,7], lv:3,
 ex:'She delegated the scheduling to her assistant.', exK:'그는 일정 관리를 비서에게 위임했습니다.',
 col:'delegate authority 권한을 위임하다', syn:'assign, hand over', conf:'명사 delegate(대표단원)로도 나옵니다'},
{id:'v141', w:'consecutive', pos:'a', mean:'연속되는', theme:'office', parts:[5,7], lv:3,
 ex:'The store has been profitable for six consecutive months.', exK:'그 매장은 6개월 연속 수익을 냈습니다.',
 col:'consecutive days 연속되는 날', syn:'successive, straight, in a row', conf:'consequent(a. 결과로 생기는)'},
{id:'v142', w:'thorough', pos:'a', mean:'철저한', theme:'manu', parts:[5,6,7], lv:2,
 ex:'A thorough inspection revealed two minor defects.', exK:'철저한 검사로 사소한 결함 두 개가 발견되었습니다.',
 col:'a thorough review 철저한 검토', syn:'complete, detailed, comprehensive', conf:'through(전치사 ~를 통해) / though(접속사 ~이지만) — 철자 함정'},
{id:'v143', w:'accurate', pos:'a', mean:'정확한', theme:'office', parts:[5,6,7], lv:1,
 ex:'The report gave an accurate account of the incident.', exK:'보고서는 사건을 정확하게 기술했습니다.',
 col:'accurate figures 정확한 수치', syn:'correct, precise, exact', conf:'accuracy(n. 정확성) / accurately(ad. 정확하게)'},
{id:'v144', w:'diligently', pos:'ad', mean:'성실하게, 부지런히', theme:'hr', parts:[5,7], lv:3,
 ex:'The crew worked diligently to finish ahead of schedule.', exK:'작업팀은 예정보다 일찍 끝내려고 성실히 일했습니다.',
 col:'work diligently 성실하게 일하다', syn:'hard, conscientiously', conf:'diligent(a. 성실한)'},
{id:'v145', w:'relocate', pos:'v', mean:'이전하다, 이주하다', theme:'house', parts:[4,6,7], lv:2,
 ex:'The company decided to relocate its headquarters.', exK:'회사는 본사를 이전하기로 결정했습니다.',
 col:'relocate to + 장소', syn:'move, transfer', conf:'relocation(n. 이전) / locate(v. 위치를 찾다)'},
{id:'v146', w:'headquarters', pos:'n', mean:'본사, 본부', theme:'biz', parts:[4,6,7], lv:2,
 ex:'Their headquarters is located in Singapore.', exK:'그들의 본사는 싱가포르에 있습니다.',
 col:'move headquarters 본사를 옮기다', syn:'head office, main office', conf:'끝의 s 를 빼지 않습니다 — 단수로도 headquarters'},
{id:'v147', w:'subsidiary', pos:'n', mean:'자회사', theme:'biz', parts:[6,7], lv:3,
 ex:'The firm operates three subsidiaries in Europe.', exK:'그 회사는 유럽에서 자회사 세 곳을 운영합니다.',
 col:'a wholly owned subsidiary 완전 자회사', syn:'affiliate, branch company', conf:'subsidy(n. 보조금)'},
{id:'v148', w:'branch', pos:'n', mean:'지점, 지사', theme:'biz', parts:[3,4,7], lv:1,
 ex:'A new branch will open in the shopping district in June.', exK:'6월에 상업 지구에 새 지점이 개설됩니다.',
 col:'open a branch 지점을 열다', syn:'office, outlet, location', conf:'brand(n. 상표)'},
{id:'v149', w:'quarterly', pos:'a', mean:'분기별의', theme:'fin', parts:[6,7], lv:2,
 ex:'Quarterly reports are due on the fifth of each quarter.', exK:'분기 보고서는 각 분기 5일이 기한입니다.',
 col:'a quarterly report 분기 보고서', syn:'every three months', conf:'quarter(n. 분기, 4분의 1)'},
{id:'v150', w:'forecast', pos:'n', mean:'예상, 예측', theme:'fin', parts:[4,6,7], lv:2,
 ex:'Figures exceeded our original forecast by ten percent.', exK:'실적이 원래 예측치를 10퍼센트 넘었습니다.',
 col:'a sales forecast 매출 예상', syn:'projection, prediction, outlook', conf:'과거형도 forecast 로 씁니다'},
{id:'v151', w:'surplus', pos:'n', mean:'잉여, 흑자', theme:'fin', parts:[7], lv:3,
 ex:'The department ended the year with a small surplus.', exK:'그 부서는 소폭 흑자로 해를 마쳤습니다.',
 col:'a budget surplus 예산 흑자', syn:'excess, leftover', conf:'deficit(n. 적자)'},
{id:'v152', w:'settle', pos:'v', mean:'정산하다, 해결하다', theme:'fin', parts:[6,7], lv:2,
 ex:'Please settle the balance before the due date.', exK:'기한 전에 잔액을 정산해 주세요.',
 col:'settle an account 계좌를 정산하다 / settle a dispute 분쟁을 해결하다', syn:'pay off, resolve', conf:'settlement(n. 정산, 합의)'},
{id:'v153', w:'transaction', pos:'n', mean:'거래', theme:'fin', parts:[6,7], lv:3,
 ex:'Every transaction is recorded in the system.', exK:'모든 거래는 시스템에 기록됩니다.',
 col:'process a transaction 거래를 처리하다', syn:'deal, exchange', conf:'transition(n. 전환)'},
{id:'v154', w:'consumption', pos:'n', mean:'소비', theme:'manu', parts:[6,7], lv:3,
 ex:'The upgrade cut energy consumption by a third.', exK:'그 개선으로 에너지 소비가 3분의 1 줄었습니다.',
 col:'energy consumption 에너지 소비', syn:'use, usage', conf:'consume(v. 소비하다) / assumption(n. 가정)'},
{id:'v155', w:'durable', pos:'a', mean:'튼튼한, 내구성 있는', theme:'manu', parts:[6,7], lv:3,
 ex:'The casing is made of a durable plastic.', exK:'케이스는 내구성 있는 플라스틱으로 만들어졌습니다.',
 col:'a durable material 내구성 있는 소재', syn:'long-lasting, sturdy, robust', conf:'durability(n. 내구성) / duration(n. 지속 기간)'},
{id:'v156', w:'operate', pos:'v', mean:'작동하다, 운영하다', theme:'manu', parts:[3,4,5], lv:1,
 ex:'The plant operates around the clock.', exK:'그 공장은 24시간 가동됩니다.',
 col:'operate machinery 기계를 조작하다 / around the clock 24시간', syn:'run, function, manage', conf:'operation(n. 운영, 수술) / operator(n. 기사, 교환원)'},
{id:'v157', w:'assemble', pos:'v', mean:'조립하다, 모이다', theme:'manu', parts:[1,4,7], lv:2,
 ex:'Workers assemble the units by hand.', exK:'작업자들이 제품을 손으로 조립합니다.',
 col:'assemble a product 제품을 조립하다', syn:'put together, gather', conf:'resemble(v. 닮다)'},
{id:'v158', w:'excessive', pos:'a', mean:'과도한', theme:'manu', parts:[5,7], lv:3,
 ex:'Excessive vibration damaged the bearings.', exK:'과도한 진동이 베어링을 손상시켰습니다.',
 col:'excessive noise 과도한 소음', syn:'too much, undue', conf:'exceptional(a. 뛰어난) / excess(n. 초과)'},
{id:'v159', w:'verify', pos:'v', mean:'확인하다, 검증하다', theme:'tech', parts:[5,6,7], lv:2,
 ex:'The system verifies each password before granting access.', exK:'시스템은 접근을 허용하기 전에 각 비밀번호를 확인합니다.',
 col:'verify an identity 신원을 확인하다', syn:'confirm, check, validate', conf:'verification(n. 확인) / clarify(v. 명확히 하다)'},
{id:'v160', w:'retrieve', pos:'v', mean:'되찾다, 검색하다', theme:'tech', parts:[6,7], lv:3,
 ex:'You can retrieve deleted files within seven days.', exK:'삭제된 파일은 7일 안에 복구할 수 있습니다.',
 col:'retrieve data 데이터를 불러오다', syn:'recover, get back', conf:'retrieval(n. 검색, 회수)'},
{id:'v161', w:'shutdown', pos:'n', mean:'가동 중단, 폐쇄', theme:'tech', parts:[4,7], lv:3,
 ex:'A malfunctioning sensor caused the shutdown.', exK:'오작동하는 센서가 가동 중단을 일으켰습니다.',
 col:'a temporary shutdown 일시적 가동 중단', syn:'closure, stoppage', conf:'shut down(동사구 — 띄어 씁니다)'},
{id:'v162', w:'subscription', pos:'n', mean:'구독', theme:'tech', parts:[6,7], lv:2,
 ex:'Your subscription renews automatically each year.', exK:'구독은 매년 자동으로 갱신됩니다.',
 col:'renew a subscription 구독을 갱신하다', syn:'membership', conf:'prescription(n. 처방전) — 발음이 비슷합니다'},
{id:'v163', w:'occupant', pos:'n', mean:'입주자, 사용자', theme:'house', parts:[7], lv:3,
 ex:'Occupants must vacate the unit by noon.', exK:'입주자는 정오까지 호실을 비워야 합니다.',
 col:'the previous occupant 이전 입주자', syn:'tenant, resident', conf:'occupation(n. 직업)'},
{id:'v164', w:'vacate', pos:'v', mean:'비우다, 퇴거하다', theme:'house', parts:[7], lv:3,
 ex:'Please vacate the conference room by three.', exK:'3시까지 회의실을 비워 주세요.',
 col:'vacate the premises 건물을 비우다', syn:'leave, clear out', conf:'vacation(n. 휴가) / vacant(a. 비어 있는)'},
{id:'v165', w:'adjacent', pos:'a', mean:'인접한, 옆에 있는', theme:'house', parts:[1,6,7], lv:3,
 ex:'The parking lot adjacent to the building is for visitors.', exK:'건물에 인접한 주차장은 방문객용입니다.',
 col:'adjacent to ~ (전치사 to)', syn:'next to, neighboring, beside', conf:'adjust(v. 조정하다)'},
{id:'v166', w:'spacious', pos:'a', mean:'널찍한', theme:'house', parts:[1,7], lv:2,
 ex:'The new office is bright and spacious.', exK:'새 사무실은 밝고 널찍합니다.',
 col:'a spacious lobby 널찍한 로비', syn:'roomy, large', conf:'special(a. 특별한)'},
{id:'v167', w:'inclement', pos:'a', mean:'(날씨가) 궂은', theme:'travel', parts:[4,7], lv:3,
 ex:'The event was moved indoors due to inclement weather.', exK:'궂은 날씨로 행사는 실내로 옮겨졌습니다.',
 col:'inclement weather 악천후', syn:'bad, severe, harsh', conf:'clement(a. 온화한)'},
{id:'v168', w:'shuttle', pos:'n', mean:'셔틀버스, 왕복 운행편', theme:'travel', parts:[3,4,7], lv:1,
 ex:'A free shuttle runs between the hotel and the terminal.', exK:'호텔과 터미널 사이에 무료 셔틀이 운행합니다.',
 col:'a shuttle service 셔틀 운행', syn:'bus, transfer', conf:'shut(v. 닫다)'},
{id:'v169', w:'baggage claim', pos:'n', mean:'수하물 수취대', theme:'travel', parts:[4], lv:2,
 ex:'Proceed to baggage claim on the lower level.', exK:'아래층 수하물 수취대로 이동하세요.',
 col:'at baggage claim 수하물 수취대에서', syn:'luggage pickup', conf:'claim(v. 주장하다, 청구하다)'},
{id:'v170', w:'connecting flight', pos:'n', mean:'연결 항공편', theme:'travel', parts:[3,4], lv:2,
 ex:'The speaker missed her connecting flight.', exK:'연사가 연결 항공편을 놓쳤습니다.',
 col:'miss a connecting flight 연결편을 놓치다', syn:'connection', conf:'direct flight(직항)'},
{id:'v171', w:'per diem', pos:'n', mean:'일일 경비, 일당', theme:'travel', parts:[7], lv:3,
 ex:'Travelers receive a per diem for meals.', exK:'출장자는 식비로 일일 경비를 받습니다.',
 col:'a daily per diem 하루 경비', syn:'daily allowance', conf:'라틴어 표현으로 그대로 씁니다'},
{id:'v172', w:'banquet', pos:'n', mean:'연회, 만찬', theme:'dine', parts:[4,7], lv:2,
 ex:'The annual banquet will be held at the Harborview.', exK:'연례 만찬은 Harborview 에서 열립니다.',
 col:'a banquet hall 연회장', syn:'formal dinner, gala', conf:'blanket(n. 담요)'},
{id:'v173', w:'buffet', pos:'n', mean:'뷔페', theme:'dine', parts:[4,7], lv:1,
 ex:'A lunch buffet for ninety guests is included.', exK:'손님 90명분 점심 뷔페가 포함되어 있습니다.',
 col:'a lunch buffet 점심 뷔페', syn:'self-service meal', conf:'동사 buffet(v. 강타하다)와 발음이 다릅니다'},
{id:'v174', w:'seating', pos:'n', mean:'좌석 배치, 좌석 수', theme:'dine', parts:[1,4,7], lv:2,
 ex:'Outdoor seating is available in warm weather.', exK:'날씨가 따뜻할 때는 야외 좌석을 이용할 수 있습니다.',
 col:'seating arrangement 좌석 배치 / seating capacity 좌석 수', syn:'seats', conf:'sitting(n. 앉아 있음)'},
{id:'v175', w:'critic', pos:'n', mean:'평론가', theme:'ent', parts:[7], lv:3,
 ex:'Critics praised the museum\'s new exhibition.', exK:'평론가들은 미술관의 새 전시를 칭찬했습니다.',
 col:'a film critic 영화 평론가', syn:'reviewer', conf:'critical(a. 비판적인, 중대한) / criticism(n. 비평)'},
{id:'v176', w:'performance', pos:'n', mean:'공연 / 성과', theme:'ent', parts:[4,6,7], lv:1,
 ex:'The evening performance begins at eight.', exK:'저녁 공연은 8시에 시작합니다.',
 col:'a live performance 실황 공연 / job performance 업무 성과', syn:'show / results', conf:'문맥에 따라 공연과 성과로 갈립니다'},
{id:'v177', w:'lineup', pos:'n', mean:'출연진, 구성', theme:'ent', parts:[4,7], lv:3,
 ex:'This year\'s festival lineup includes four local bands.', exK:'올해 축제 출연진에는 지역 밴드 네 팀이 포함됩니다.',
 col:'a full lineup 전체 구성', syn:'program, roster', conf:'line up(v. 줄을 서다)'},
{id:'v178', w:'dependent', pos:'n', mean:'피부양자', theme:'health', parts:[7], lv:3,
 ex:'Coverage may be extended to dependents.', exK:'보장은 피부양자에게까지 확대될 수 있습니다.',
 col:'a dependent child 피부양 자녀', syn:'family member', conf:'형용사 dependent on(~에 의존하는)'},
{id:'v179', w:'pharmacy', pos:'n', mean:'약국', theme:'health', parts:[3,4], lv:1,
 ex:'The pharmacy closes at seven on weekdays.', exK:'약국은 평일 7시에 문을 닫습니다.',
 col:'at the pharmacy 약국에서', syn:'drugstore, chemist', conf:'pharmacist(n. 약사)'},
{id:'v180', w:'consult', pos:'v', mean:'상의하다, 참고하다', theme:'health', parts:[5,6,7], lv:2,
 ex:'Consult the manual before adjusting the settings.', exK:'설정을 바꾸기 전에 설명서를 참고하세요.',
 col:'consult a doctor 의사와 상의하다', syn:'refer to, seek advice from', conf:'consultant(n. 자문가) / consultation(n. 상담)'},
{id:'v181', w:'wellness', pos:'n', mean:'건강, 웰니스', theme:'health', parts:[7], lv:3,
 ex:'The company launched a wellness program for staff.', exK:'회사는 직원을 위한 건강 프로그램을 시작했습니다.',
 col:'a wellness program 건강 증진 프로그램', syn:'health, well-being', conf:'illness(n. 질병)'},
{id:'v182', w:'commission', pos:'n', mean:'수수료 / 위원회', theme:'biz', parts:[6,7], lv:3,
 ex:'Sales staff earn a commission on every contract.', exK:'영업 직원은 모든 계약에 수수료를 받습니다.',
 col:'earn a commission 수수료를 받다', syn:'fee, percentage', conf:'동사 commission(v. 의뢰하다)로도 나옵니다'},
{id:'v183', w:'testimonial', pos:'n', mean:'추천의 글, 후기', theme:'biz', parts:[7], lv:3,
 ex:'Customer testimonials appear on the product page.', exK:'고객 후기가 제품 페이지에 실려 있습니다.',
 col:'a customer testimonial 고객 후기', syn:'review, endorsement', conf:'testimony(n. 증언)'},
{id:'v184', w:'inquiry', pos:'n', mean:'문의', theme:'biz', parts:[6,7], lv:2,
 ex:'Direct all inquiries to the customer service desk.', exK:'모든 문의는 고객 서비스 데스크로 보내 주세요.',
 col:'make an inquiry 문의하다 / an inquiry about ~', syn:'question, query', conf:'enquiry 로도 쓰지만 시험에는 inquiry 가 나옵니다'},
{id:'v185', w:'obtain', pos:'v', mean:'얻다, 획득하다', theme:'biz', parts:[5,6,7], lv:2,
 ex:'You must obtain written permission from the owner.', exK:'소유주로부터 서면 허가를 받아야 합니다.',
 col:'obtain approval 승인을 얻다', syn:'get, acquire, secure', conf:'attain(v. 달성하다) / abstain(v. 삼가다)'},
{id:'v186', w:'liaison', pos:'n', mean:'연락 담당(자)', theme:'office', parts:[7], lv:3,
 ex:'Ms. Wu will act as liaison between the two offices.', exK:'Wu 씨가 두 사무소 사이의 연락 담당을 맡습니다.',
 col:'act as liaison 연락 담당을 맡다', syn:'contact person, intermediary', conf:'liable(a. 책임이 있는)'},
{id:'v187', w:'proceeds', pos:'n', mean:'수익금', theme:'fin', parts:[7], lv:3,
 ex:'All proceeds from the sale go to a local charity.', exK:'판매 수익금 전액은 지역 자선단체로 갑니다.',
 col:'proceeds from ~의 수익금', syn:'earnings, income', conf:'proceed(v. 진행하다) / procedure(n. 절차)'},
{id:'v188', w:'itemized', pos:'a', mean:'항목별로 구분된', theme:'purch', parts:[7], lv:3,
 ex:'Attach an itemized invoice to your claim.', exK:'청구서에 항목별 송장을 첨부하세요.',
 col:'an itemized statement 항목별 명세서', syn:'detailed, broken down', conf:'itemize(v. 항목별로 적다)'},
{id:'v189', w:'redeem', pos:'v', mean:'(쿠폰을) 사용하다, 교환하다', theme:'purch', parts:[6,7], lv:3,
 ex:'The voucher may be redeemed at any branch.', exK:'그 상품권은 어느 지점에서든 사용할 수 있습니다.',
 col:'redeem a coupon 쿠폰을 사용하다', syn:'use, exchange, cash in', conf:'redemption(n. 사용, 상환)'},
{id:'v190', w:'restock', pos:'v', mean:'재입고하다', theme:'purch', parts:[4,7], lv:2,
 ex:'The garden center closes early for seasonal restocking.', exK:'원예 매장은 계절 상품 재입고로 일찍 문을 닫습니다.',
 col:'restock shelves 진열대를 다시 채우다', syn:'replenish, refill', conf:'stock(n. 재고)'},
{id:'v191', w:'ahead of schedule', pos:'phr', mean:'예정보다 앞서', theme:'office', parts:[4,6,7], lv:2,
 ex:'The project was completed ahead of schedule.', exK:'그 사업은 예정보다 앞서 완료되었습니다.',
 col:'finish ahead of schedule 예정보다 일찍 끝내다', syn:'early, sooner than planned', conf:'behind schedule(예정보다 늦게)'},
{id:'v192', w:'on short notice', pos:'phr', mean:'급하게, 촉박하게', theme:'office', parts:[3,7], lv:3,
 ex:'Thank you for covering the shift on short notice.', exK:'급하게 근무를 대신해 주셔서 감사합니다.',
 col:'on short notice 갑작스럽게', syn:'at the last minute', conf:'until further notice(추후 안내가 있을 때까지)'},
{id:'v193', w:'as of', pos:'phr', mean:'~부터, ~ 시점에', theme:'biz', parts:[6,7], lv:2,
 ex:'The new rate takes effect as of January 1.', exK:'새 요율은 1월 1일부터 적용됩니다.',
 col:'as of + 날짜', syn:'effective, starting from', conf:'as for(~에 관해서는)'},
{id:'v194', w:'be scheduled to', pos:'phr', mean:'~할 예정이다', theme:'office', parts:[4,5,7], lv:1,
 ex:'The keynote speech is scheduled to begin at 9:30.', exK:'기조연설은 9시 30분에 시작할 예정입니다.',
 col:'be scheduled for + 시점 / be scheduled to + 동사원형', syn:'be due to, be set to', conf:'전치사 for 와 to 부정사를 구분하세요'},
{id:'v195', w:'take effect', pos:'phr', mean:'시행되다, 효력이 발생하다', theme:'biz', parts:[6,7], lv:2,
 ex:'The revised policy takes effect next Monday.', exK:'개정된 정책은 다음 주 월요일부터 시행됩니다.',
 col:'take effect immediately 즉시 시행되다', syn:'come into force, become effective', conf:'take affect 는 틀린 표현입니다'}
];

/* ---------------- 접근 함수 ---------------- */
/* 기본 제공 어휘 묶음 — 확장 파일(app_toeic_voca2.js)의 배열까지 합칩니다.
   같은 <script> 안에 이어 붙여 실행되므로, 호출 시점에는 모두 준비되어 있습니다. */
function toVocaSeeds(){
  var out = TO_VOCA_SEED.concat(TO_VOCA_SEED2);
  try{ out = out.concat(TO_VOCA_SEED3, TO_VOCA_SEED4, TO_VOCA_SEED5, TO_VOCA_SEED6, TO_VOCA_SEED7, TO_VOCA_SEED8); }catch(e){}
  return out;
}
function toVocaAll(){ return toVocaSeeds().concat(DB.toeicVoca||[]); }
function toVocaById(id){ return toVocaAll().find(function(v){ return v.id===id; }) || null; }
function toVocaByTheme(k){ return toVocaAll().filter(function(v){ return v.theme===k; }); }
function toVocaStat(){
  var all = toVocaAll(), out = { total: all.length, byTheme:{}, byLv:{1:0,2:0,3:0} };
  TO_THEMES.forEach(function(t){ out.byTheme[t.k] = 0; });
  all.forEach(function(v){
    if(out.byTheme[v.theme]!=null) out.byTheme[v.theme]++;
    out.byLv[v.lv||1] = (out.byLv[v.lv||1]||0) + 1;
  });
  return out;
}
